kind = "web"
previewPath = "/"
title = "The Necio Cobranza"
version = "1.0.0"
id = "artifacts/necio-app"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 21409

[services.development]
run = "pnpm --filter @workspace/necio-app run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/necio-app", "run", "build" ]
publicDir = "artifacts/necio-app/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "21409"
BASE_PATH = "/"
